### ISSUE TITLE
With orgmode?

### ISSUE THREAD

**Issue by wbehrens-on-gh** [shushcat/mla_paper_template#3]
Would you by chance know how to use this with orgmode? i've been trying to use pandoc to convert org files and I'm still new to it

**Comment by shushcat** [comment]
Hey, if you still need to be able to edit files in Org format as opposed to Markdown, you have many options.  

One option would be to manually convert your Org file to Markdown when you are ready to finalize your document.  In that case, you could use Pandoc (something like `pandoc -f org -t markdown input_file.org >> output_file.md`) or use [Org Mode's built in exporter](https://orgmode.org/manual/The-Export-Dispatcher.html).  If memory serves from when I was using Org Mode and Emacs, you invoke the exporter with `C-x C-e`; there are prompts available from there.   Once you have your Markdown file in hand, you can use this repository as it is to generate a PDF.

If you don't like the extra steps involved in the above options, you could fork this repository and change it to work with Org files, but I would rather not become embroiled in that process aside from pointing you in the right direction.
